<MainScreen>:
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        id: start_button
        text: "Loop once"
        size: 300, 200
        center_x: root.width * 0.5
        center_y: root.height * 0.75
        text_color: 1, 1, 1, 1
        fill_color: "paleturquoise"
        border_radius: root.width
        fill_radius: root.height
        font_size: 40
        on_press: root.check_start()
        bold: True

    DPEAButton:
        id: staircase_button
        text: 'Staircase up'
        size: 300, 200
        center_x: root.width * 0.3
        center_y: root.height * 0.5
        text_color: 1, 1, 1, 1
        fill_color: "violet"
        font_size: 40
        border_radius: 2*root.height
        fill_radius: 2*root.height
        bold: True
        on_press: root.staircase()

    DPEAButton:
        id: gate_button
        text: 'Open gate'
        size: 300, 200
        center_x: root.width * 0.7
        center_y: root.height * 0.5
        text_color: 1, 1, 1, 1
        fill_color: "violet"
        font_size: 40
        border_radius: 2*root.height
        fill_radius: 2*root.height
        bold: True
        on_press: root.gate()

    DPEAButton:
        id: ramp_button
        text: 'Ramp up'
        size: 300, 200
        center_x: root.width * 0.5
        center_y: root.height * 0.5
        text_color: 1, 1, 1, 1
        fill_color: "violet"
        font_size: 40
        border_radius: 2*root.height
        fill_radius: 2*root.height
        bold: True
        on_press: root.ramp()

    Label:
        id: ramp_label
        text_size: self.size
        font_size: 20
        color: "black"
        text: "Ramp Speed: " + str(ramp_speed.value)
        pos_hint: {"center_x":0.5, "center_y": 0.25}
        valign: "middle"
        halign: "center"

    Slider:
        id: ramp_speed
        max: 6
        min: 2
        step: 1
        size_hint_x: 0.75
        size_hint_y: 0.05
        pos_hint: {"center_x":0.5, "center_y": 0.3}


    Label:
        id: staircase_label
        text_size: self.size
        font_size: 20
        color: "black"
        text: "Staircase Speed: " + str(staircase_speed.value)
        pos_hint: {"center_x":0.5, "center_y": 0.1}
        valign: "middle"
        halign: "center"


    Slider:
        id: staircase_speed
        max: 1
        min: 0
        step: 0.1
        size_hint_x: 0.75
        size_hint_y: 0.05
        pos_hint: {"center_x":0.5, "center_y": 0.15}
