<MainScreen>:
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        id: auto_manual_toggle
        text: "Set Manual Mode"
        size_hint: (0.2, 0.1)
        pos_hint: {"x": 0.5-0.1, "y": 0.7-0.05}
        text_color: "black"
        fill_color: root.bluish_grey
        font_size: 21
        halign: 'center'
        on_press: root.toggle_auto_manual()


    DPEAButton:
        id: auto_start_stop
        text: "Start"
        width: root.width* 0.1
        height: root.height * 0.1
        x: root.width * (0.5 - 0.05)
        y: root.height * (0.5 - 0.05)
        text_color: "black"
        fill_color: root.green
        on_press: root.start_stop_auto()

    #DPEAButton:

    Label:
        id: ramp_speed_label
        color: "black"
        pos_hint: {"x": 0.05, "y": 0.05}
        halign: "left"
        text: f"Set Ramp Speed: {int(ramp_speed_slider.value)}%"
        font_size: 21
        text_size: self.size
        size_hint: (0.2, 0.1)
        valign: "middle"

    Slider:
        id: ramp_speed_slider
        min: 0
        max: 100
        step: 1
        size_hint: (0.7, 0.1)
        pos_hint: {"right": 1, "y": 0.05}
        halign: "right"

    Label:
        id: stair_speed_label
        color: "black"
        pos_hint: {"x": 0.05, "y": 0.025}
        halign: "left"
        valign: "bottom"
        text: f"Set Stair Speed: {int(stair_speed_slider.value)}%"
        font_size: 21
        text_size: self.size
        size_hint: (1, 0.1)

    Slider:
        id: stair_speed_slider
        min: 0
        max: 100
        step: 1
        size_hint: (0.7, 0.05)
        pos_hint: {"right": 1, "y": 0.025}
        halign: "right"

<Slider>
    value_track: True
