<MainScreen>:
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        id: test_button_1
        text: "Hello"
        size: 200, 200
        x: root.width * 0.4
        y: root.height * 0.5
        text_color: 1, 1, 1, 1
        fill_color: 1, 0, 0, 1
        border_radius: root.height/2
        fill_radius: root.height/2
        font_size: 30
        on_press: root.pressed()

    DPEAButton:
        id: test_button_2
        text: 'World'
        size: 100, 200
        x: root.width * 0.6
        y: root.height * 0.5
        text_color: 1, 1, 1, 1
        fill_color: 0, 0, 1, 1
        font_size: 20
        bold: True
        on_press: root.pressed()

    DPEAButton:
        id: test_button_3
        size: ((test_button_2.x + test_button_2.width) - test_button_1.x) + 150, 100
        fill_color: 1, 1, 0, 1
        border_radius: 50
        fill_radius: 50
        center_x: test_button_2.x + (test_button_1.x - test_button_2.x)/2 + 75
        y: root.height * 0.25